version: '4.21.1'

services:
  postgres:
    image: 'postgres:alpine'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgresmaster'
      - 'POSTGRES_DB=tododb'
    ports:
      - '5432:5432'